### ISSUE TITLE
findNode multiple queries

### ISSUE THREAD

**Issue by holyxiaoxin** [glenjamin/skin-deep#16]
It would be useful if findNode accepts an array of queries to match.
Eg. `tree.findNode(['.foo','#bar'])`
=> returns all nodes which match `.foo` and `#bar`.
Thanks.

**Comment by glenjamin** [comment]
Seems doable, will fold into #9

**Comment by holyxiaoxin** [comment]
Great! (:

**Comment by glenjamin** [comment]
Was thinking about this today while writing up notes for a `v1.0` API.

What scenarios do you need this for? Could you just make multiple calls to `everySubTree`?

**Comment by glenjamin** [comment]
I've decided this doesn't make the cut for now, if it's demanded highly it could be added - but it'll be possible to do by passing a function as the props matcher in the new scheme.

I'll export the className matcher as that has well tested logic for HTML's class rules.
