### ISSUE TITLE
Invalid node query for react-redux wrapped components

### ISSUE THREAD

**Issue by nickjvm** [glenjamin/skin-deep#18]
Components wrapped in  react-redux's `Connect()` method have a display name with parenthesis.

```
let tree = sd.shallowRender(React.createElement(View, props));
expect(tree.findNode('Connect(ReduxComponent)')).to.not.equal(false);
```

In this case, having parenthesis in the display name is perfectly valid.

Possible solution: add parenthesis as valid characters in Regex test. Not sure if this will have other negative implications elsewhere.
```
if (query.match(/^[A-Z][\w\-\(\)]*$/)) { // component displayName
    return function(n) { return n.type && getComponentName(n.type) == query; };
}
```

**Comment by glenjamin** [comment]
I think we can actually just make the fallthrough case be displayName instead of an error.

In general I'd recommend testing components without connecting to the store - but no reason not to take this improvement.

Will accept a PR, or fix myself at some point soonish.
