### ISSUE TITLE
proper linting in the CI build

### ISSUE THREAD

**Issue by glenjamin** [glenjamin/skin-deep#41]
Run eslint as part of CI.

Make sure the rules are correct for a 1.0+ ES5 lib.

**Comment by burabure** [comment]
May I suggest airbnb's linting rules? https://www.npmjs.com/package/eslint-config-airbnb

**Comment by glenjamin** [comment]
Thanks for the suggestion, but I have my own config set configured, have just added it: https://github.com/glenjamin/skin-deep/commit/991dba51f1759aa1fc79e20313e5e2e3b9e7a3e1
