### ISSUE TITLE
ReactContext has been removed

### ISSUE THREAD

**Issue by 3rd-Eden** [glenjamin/skin-deep#42]
facebook/react#3999 Removed the Context module from the source, causing this module not work React 0.14.x

**Comment by glenjamin** [comment]
Are you using a module bundler?

This module detects the react version at runtime and only includes context in 0.13.

See https://github.com/glenjamin/skin-deep#errors-when-bundling if you need to teach a static analysis tool about this.

**Comment by 3rd-Eden** [comment]
I'm using it as standalone. Just `npm install skin-deep` and using it directly in `mochify` which uses browserify to build assets.

**Comment by glenjamin** [comment]
You'll need to get the appropriate config into mochify for it to pass through to browserify then.

The tests are currently running and passing on 0.13 and 0.14 without module bundling. I'll be dropping 0.13 support at some point, but not imminently.

**Comment by 3rd-Eden** [comment]
OK, got it working.. So for the sake posterity if you want to use this module together with [mochify](https://npm.im/mochify) you need to use it's API instead of CLI interface as it exposes no methods for exclusion. Your custom test runner file should look something like: 

```js
'use strict';

var mochify = require('mochify');

var browserify = mochify('./test.js', {
  reporter: 'spec',
  ui: 'bdd',
  transform: 'babelify'
});

browserify.exclude('react/lib/ReactContext');
browserify.bundle();
```

The spec, ui, and transform are all optional. Closing this issue as the snipped above unbroke all the things. Sorry for wasting an issue on this.

**Comment by glenjamin** [comment]
Not a problem, I'm a big primus fan so we'll call it even :stuck_out_tongue:
