### ISSUE TITLE
subTree requires all classNames to be passed

### ISSUE THREAD

**Issue by simonsmith** [glenjamin/skin-deep#46]
If I have an element with multiple classNames it seems I have to pass all of them to `subTree` for it to  match:

```js
React.DOM.div({className: 'Test Component'});
```

```js
// This doesn't match (would expect it to)
tree.subTree('.Test');

// This does, but quite verbose
tree.subTree('.Test.Component');
```

**Comment by glenjamin** [comment]
This should be working, there were some changes made to className handling this morning - can you confirm that this is still broken on `0.13.2` ?

**Comment by simonsmith** [comment]
Ah I missed that release, sorry. Yeah it works fine! Cheers
