### ISSUE TITLE
tree.text() has some bugs ...

### ISSUE THREAD

**Issue by zhaotai** [glenjamin/skin-deep#47]
When I use the text function of tree class, there will be a space between 2 string.
eg. 
```
// Example.jsx 
...
render(<Example>{profit}%</Example>);
```

```
//Example.test.js
......
var props = { attr: 9.8 };
var tree = sd.shallowRender(
  <Example {...props} />
);
tree.text(); // "9.8 %"
```
The actual output I want is "9.8%" and there isn`t any space between "9.8" and "%". But the truth is not. I guess there maybe have been something wrong when that function parsed the children array to string.

**Comment by glenjamin** [comment]
I was fairly sure I'd fixed this recently, let me check - it might have only been on the 1.0 branch.

**Comment by zhaotai** [comment]
Maybe, my version is 0.13. By the way, this is such a useful package. Hope you will update better.

**Comment by glenjamin** [comment]
Turn out this bugfix was only on the (unreleased) 1.0 branch, I've just ported it back to the mainline, and will release 0.14 shortly.

I'm hoping to work more on the 1.0 branch soon and get it into a state where I can release a preview version. There's a few breaking changes to be made, and I want to ensure there's great test coverage.

**Comment by glenjamin** [comment]
`0.14.0` has been published with this fix.
