### ISSUE TITLE
react 0.14 system.js/jspm dependency issue README update

### ISSUE THREAD

**Issue by chauthai** [glenjamin/skin-deep#49]
I've installed skin-deep in a system.js enviroment with react 0.14 karma-jspm, phantomjs etc.
To make it work I had to override a dependency when installing skin-deep:

`jspm install npm:skin-deep -o "{map: {'react/lib/ReactContext': '@empty'}}"`

More here in the [system.js issue](https://github.com/systemjs/systemjs/issues/983).
Maybe it's worth to put it into the README.md.

**Comment by glenjamin** [comment]
Closed via 9deb52e
