### ISSUE TITLE
Allow partial prop matches

### ISSUE THREAD

**Issue by simonsmith** [glenjamin/skin-deep#50]
Given this element:

``` js
React.createElement(Test, {foo: true, bar: true});
```

Would be good to search for it with one prop:

```js
tree.subTree('Test', {foo: true});
```

But currently I have to use exact:

```js
tree.subTree('Test', {foo: true, bar: true});
```

Is this possible? Perhaps I'm using it incorrectly.

**Comment by glenjamin** [comment]
The method you're looking for is called `subTreeLike`.

As this is the more common case, in 1.0 the behaviour will change and what you've done will be correct.

**Comment by simonsmith** [comment]
Ah okay, so in 1.0 we can expect `subTree` and `everySubTree` to be the only traversal methods? I've been sticking to those two so far to avoid major refactors ahead

**Comment by simonsmith** [comment]
It seems to work in [the tests too](https://github.com/glenjamin/skin-deep/blob/master/test/test.js#L458-L465)

**Comment by glenjamin** [comment]
There will still be some way of doing exact prop matching, and i'll likely keep the Like variants around to ease migration

**Comment by simonsmith** [comment]
Cool, thanks :+1:
