### ISSUE TITLE
Testing Refs

### ISSUE THREAD

**Issue by baldore** [glenjamin/skin-deep#51]
Hi!

I don't know why the refs object appears empty. This is my code:

### Form component

```javascript
<form onSubmit={this.submitHandler}>
  <input type="text" ref="input" />
  <button className="s-button">Add</button>
</form>
```

### Before Each

```javascript
this.spy = expect.createSpy();
this.tree = sd.shallowRender(<Form onSubmit={this.spy} />);
this.instance = this.tree.getMountedInstance();
this.vdom = this.tree.getRenderOutput();
```

### Test

```javascript
const { instance, tree, vdom } = this;
instance.refs; // Returns an empty object
// Method of Form. Throws 'undefined' is not an object.
// evaluating 'this.refs.input.value = '''
instance.cleanForm(); 
```

Do you have any idea? I tested it using renderIntoDocument and worked fine. Thanks!

**Comment by glenjamin** [comment]
Does this work if you use shallow rendering without `skin-deep`?

**Comment by glenjamin** [comment]
Thinking about it a bit more, `ref`s can't really work with shallow rendering - as they'd be references to DOM elements - but there are no DOM elements to ref.

You could fake the behaviour by putting a stub into the instance with something like:

```js
this.instance.refs = {};
this.instance.refs.input = {};
```

**Comment by baldore** [comment]
Nice! Thanks!
