### ISSUE TITLE
Cannot resolve module ReactContext

### ISSUE THREAD

**Issue by alexmngn** [glenjamin/skin-deep#58]
Hi there,
Even though I've added to my `webpack.config.js` file the required IgnorePlugin, I keep having the error 

> ERROR in ./~/skin-deep/skin-deep.js
> Module not found: Error: Cannot resolve module 'react/lib/ReactContext' in /Users/Alex/Workspace/ui/node_modules/skin-deep

Is this file the right one to add the IgnorePlugin method?
I'm using React 0.14.

**Comment by glenjamin** [comment]
Can you post your whole webpack config?

**Comment by alexmngn** [comment]
```
'use strict';

var webpack = require('webpack');

module.exports = {

  devtool: 'eval-source-map',

  entry: {
    App: ['./src/App.jsx'],
  },

  output: {
    path: './dist/',
    filename: '[name].js'
  },

  module: {
    loaders: [
      {
        test: /(\.js|\.jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },

      {
        test: /\.scss$/,
        loaders: [
          'style?sourceMap',
          'css?modules&importLoaders=1&localIdentName=[local]',
          'resolve-url',
          'sass?sourceMap'
        ]
      }
    ]
  },

  plugins: [
    new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en|de|fr|zh|ja|it/)
  ],

  resolve: {
    extensions: ['', '.js', '.json', '.jsx']
  }

};
```

**Comment by glenjamin** [comment]
How are you bundling the tests? Does the test bundle use this webpack config?

Might be a similar issue to https://github.com/glenjamin/skin-deep/issues/42

**Comment by alexmngn** [comment]
You're right, it was using the `karma.conf.js` file while running the tests! Thanks for your help
