### ISSUE TITLE
Redux Connect support

### ISSUE THREAD

**Issue by massanishi** [glenjamin/skin-deep#62]
Love using the subTree function. Now the query matchs only applies to the string match with displayName. However, if the component is included with redux connect, it only matches to:

> tree.subTree('Connect(Client)');

Not:

> tree.subTree('Client');

I know it's due to the fact that redux wraps component's display name with connect. Still, I feel like the testing file shouldn't need to know if the imported file comes from connect component or normal component. It would be great to have a connect name check in the createNodePredicate.

Thanks!

**Comment by glenjamin** [comment]
Hrm, interesting.

To me this indicates that we're not asserting on the right thing. But I'm not entirely sure what the right thing to assert on should be.

Is there any convention for HoCs to expose the wrapped type under a consistent name?

If you don't want the consumer of a component to know if it's wrapped, you could override the display name to not include `connect()`.

**Comment by glenjamin** [comment]
I've just pushed a commit which allows you to pass the component type as the selector instead of only the string display name. This is similar to the older `findComponent` API, but I think shouldn't suffer from the same issues that led us to phase that out. You'll still have to import your expected component, but you can't be bitten by default props.

So instead of this
```js
tree.subTree('Connect(Client)');
```

You can now do this
```js
var Client = require('../app/components/Client');
tree.subTree(Client);
```

I've published this as `0.16.0` - let me know if this works for you.

**Comment by massanishi** [comment]
A great fix!
I was looking for something like findComponent before, especially because other testing libraries use it in a similar way. I am glad you made it a comeback. It works like charm now.
Thanks for the quick response:)

**Comment by renanvalentin** [comment]
Hey guys, do I have to wrap my shallow render with a Provider ?

I'm receiving this errors message:

` Could not find "store" in either the context or props of "Connect(AddToCartPopoverSaveAction)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(AddToCartPopoverSaveAction)".`

**Comment by glenjamin** [comment]
I'd probably aim to pass the store as a prop.

**Comment by renanvalentin** [comment]
It worked @glenjamin , thanks!!
