### ISSUE TITLE
shallowRender with props

### ISSUE THREAD

**Issue by bep** [glenjamin/skin-deep#75]
I may miss something here, but the reRender takes props as second argument, but the initial shallowRender does not:

https://github.com/glenjamin/skin-deep#shallowrenderelement--context

**Comment by glenjamin** [comment]
The terminology used is from http://facebook.github.io/react/docs/glossary.html

notably:

* `ReactComponent` is a component definition
* `props` is an object of key/value pairs
* `ReactElement` is what you get when you do `React.createElement(ReactComponent, props)`

The initial render receives an element, which tells it what component and props to use. When re-rendering you cannot change the component, so the API only allows you to pass new props.

Does that make sense?

**Comment by bep** [comment]
Yea, right -- that is also how I have mapped in my Go bindings, sorry for the confusion.
