### ISSUE TITLE
elementOrFunction() is not defined

### ISSUE THREAD

**Issue by bep** [glenjamin/skin-deep#77]
See https://github.com/glenjamin/skin-deep/blob/master/skin-deep.js#L19

**Comment by glenjamin** [comment]
Sounds like you've passed something undefined to `shallowRender`.

**Comment by bep** [comment]
That is not the point of this issue; an informative error message of some sorts is better then a cryptic "not defined" error.

**Comment by bep** [comment]
Just close if this is the preferred way of handling errors.

**Comment by glenjamin** [comment]
I'm not really a fan of putting defensive checks for null-pointer-errors in javascript functions.

Could you provide the sample code which hit this problem? If this particular case comes up a lot I could be persuaded.

**Comment by bep** [comment]
OK, JavaScript isn't my world, but calling made-up functions is confusing for the user and, not the least, extremely confusing for the people trying to read your source: "What does that function do? Oh ... where is it?"

**Comment by glenjamin** [comment]
`elementOrFunction` is a param.

The render API is `shallowRender(elementOrFunction, context)`.

If you call it with `undefined` as the first argument, you get that error. This is basically a problem in any language with a `null` value.

If there is a particularly common case that leads to people accidentally calling this function with `null`, A check and a warning could be added - but I don't think that is the case.

**Comment by glenjamin** [comment]
Another option might be to flip the check around, and only call it if it is a function - otherwise to assume it's ok and pass along to the underlying React shallow rendering - which may or may not trigger it's own error.

**Comment by glenjamin** [comment]
And actually, the `function` API only existing for React 0.13's context handling, so I might remove that entirely instead.

**Comment by bep** [comment]
OK, I see it now, my bad. Sorry.
