### ISSUE TITLE
ref and key parameters in predicate

### ISSUE THREAD

**Issue by droarty** [glenjamin/skin-deep#78]
Hi, I am loving skin-deep.  But I often struggle to navigate to a node when ref or key are the only unique things on the node.   I have found that these two parameters are not available on the shallowly rendered node.   Is there a work around or are there any plans to add these parameters as searchable in the predicate object?

**Comment by glenjamin** [comment]
You can pass an arbitrary function as the marcher argument, so should be able to read them that way.

Can you give me a concrete example of when this comes up?

**Comment by droarty** [comment]
Ah, just tested this.  Very slick.  I didn't understand what happened to the key and ref parameters (nothing about them in the documentation.  By trial and error, I knew they did not become part of the props but didn't know where they went.

The reason I want to fetch by ref or key is that sometimes these are the only unique identifiers on a node I want to test.   This may not be the best approach but if I have a bunch of input fields I can use ref as my way of associating a particular input with a particular state value.  And I end up with ref being the only unique identifier on the input field.  So:

```javascript
let MyForm = React.createClass({
  getDefaultProps() {
    return {
      activity: {
        name: '',
        phone: '',
        address: ''
      }
    }
  },

  getInitialState() {
    return this.props.activity
  },

  onFieldChange() {
    var newState = Object.keys(this.refs).reduce((state, key)=> {
      state[key] = this.refs[key].value
      return state
    }, this.state)
    this.setState(newState)
  },

  render() {
    return (
      <div>
      <input type="text" 
             ref="name"
             onChange={this.onFieldChange}
             value={this.state.name}/>
      <input type="text" 
             ref="phone"
             onChange={this.onFieldChange}
             value={this.state.phone}/>
      <input type="text" 
             ref="address"
             onChange={this.onFieldChange}
             value={this.state.address}/>
      </div>
    )
  }
})

describe('MyForm', function() {
  describe('name input field', function() {
    it('updates the state name value', function() {
      let activity = {name: 'foo', phone: '123', address: 'abc'}
      let myForm = sd.shallowRender(<MyForm activity={activity}/>)

      // The following will not work
      let nameInput = myForm.subTree('input', {ref: 'name'})

      // So you are proposing
      let nameInput = myForm.subTree('input', function(node) {
        return node.ref == 'name'
      })

      expect(nameInput.props.value).to.equal('foo')
    })
  
  })
})
```

**Comment by glenjamin** [comment]
You can wrap up the ref function in a helper if you wish:
```js
function byRef(ref) {
 return function(node) { return node.ref == ref };
}
// Then use:
myForm.subTree("input", byRef("name"));
```

In your example above you don't actually need the refs for the state handling, because you can read the input value from the change event:

```js
  onFieldChange(e) {
    this.setState({ [e.target.name]: e.target.value })
  },
```

To make this work you'd need to put a `name` field on each element, which you could then use in skin deep to find them.
