### ISSUE TITLE
Fix React 15.5 deprecations

### ISSUE THREAD

**Issue by philipp-spiess** [glenjamin/skin-deep#86]
Hey! React 15.5 just came out and moved the shallow renderer to `react-test-renderer/shallow`. See [this line here](https://github.com/airbnb/enzyme/pull/876/files#diff-8cc0b6373aabc9fe260bdd27be28c6f9R99) for reference.

**Comment by glenjamin** [comment]
Cheers for the link, that should be a good reference.

A PR would be appreciated by anyone who'd like to pick this up.

**Comment by modosc** [comment]
i'm looking at this now

**Comment by modosc** [comment]
https://github.com/glenjamin/skin-deep/pull/87

**Comment by glenjamin** [comment]
Should now be resolved thanks to the great work from @modosc in #87

Released as `v1.0.0`.
