### ISSUE TITLE
Support React 15.6 and up

### ISSUE THREAD

**Issue by philipp-spiess** [glenjamin/skin-deep#90]
Now that a new minor version of React was released, the version check that we have in [place right now](https://github.com/glenjamin/skin-deep/blob/master/test/react-compat.js#L7) is no longer sufficient. We should update this to match all future versions of React (both minor and major version bumps). 

As a solution, we could add the [`semver`](https://www.npmjs.com/package/semver) package and rename the variable to `Versions.ReactGte155`.

**Comment by glenjamin** [comment]
I'm going to flip the conditional to check for <=15.5, should be more reliable.

**Comment by glenjamin** [comment]
Turned out to be a little fiddly, as the non-core modules now get versioned at different rates.

This is now released as `v1.1.0`
