### ISSUE TITLE
./install-relevant-react.sh: line 15: node_modules/.bin/semver: No such file or directory

### ISSUE THREAD

**Issue by probedb** [glenjamin/skin-deep#92]
Hi Glen,

Getting this locally and on our build boxes. For some reason it also seems to install 15.6 even though it's "react": "15.4.0" in the package.json.

This leads to a later 

    Error: Cannot find module 'react-test-renderer/shallow'

When running tests.

Any thoughts?

Cheers.

**Comment by glenjamin** [comment]
sounds like you're trying to run tests on `skin-deep` itself without having all the packages installed.

`./install-relevant-react.sh` should only ever be run as part of this module's test suite.


What is it you're trying to do?

**Comment by probedb** [comment]
The output is when I do an npm i :/ Node 6.11.1 and npm 3.10.11 I think

**Comment by probedb** [comment]
And then running `npm run test` causes:

Error: Cannot find module 'react-test-renderer/shallow'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pso06/skybet/casino-webapp/node_modules/skin-deep/lib/react-compat.js:11:27)

**Comment by glenjamin** [comment]
Aha, you're right - this is because I added install as a `postinstall` script, which doesn't work right for consumers.

I'll get this fixed.

**Comment by probedb** [comment]
Excellent, cheers Glen 👍

**Comment by glenjamin** [comment]
Released as `v1.1.1`

**Comment by probedb** [comment]
👍
