### ISSUE TITLE
Warnings in React 15.5 due to accessing createClass and propTypes via the main React package

### ISSUE THREAD

**Issue by kfranco619** [glenjamin/skin-deep#95]
In react 15.5, instead of accessing PropTypes from the main React object, install the prop-types package and import them from there. Similar method for createClass. This would allow a smooth transition to continue the use of skin-deep in react 16.0.

https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

**Comment by glenjamin** [comment]
Skin deep has already been updated to work with 16 as far as I know since https://github.com/glenjamin/skin-deep/pull/94

If there is more work needed here then i’m happy to take PRs with tests

**Comment by kfranco619** [comment]
You are right! You are handling the different versions of React just fine!
